#!/bin/zsh

# ESCREVER UM SCRIPT QUE RECEBA UM DIRETÓRIO COMO ARGUMENTO/PARÂMETRO
# DEFINIR ESSE PRIMEIRO ARGUMENTO COMO VARIAVEL DIRECTORY
DIRECTORY=$1
# CASO ARGUMENTO NAO SEJA UM DIRETÓRIO PRINTAR "O ARGUMENTO X NÃO É UM DIRETORIO"
if ! [ -d $DIRECTORY ]
    then
        echo "$DIRECTORY Não é um diretório."
# CASO ARGUMENTO SEJA DIRETÓRIO CONTAR QUANTOS ARQUIVOS EXISTEM NELE E PRINTAR
elif [ -d $DIRECTORY ]
    then
        # DEFINIR VARIAVEL FILES_SUM QUE REPRESENTA A SOMA DOS ARQUIVOS DA VARIÁVEL DIRECTORY
        FILES_SUM=$(ls $DIRECTORY | wc -l)
        # PRINT SOMA DO DIRETÓRIO
        echo "O diretório $DIRECTORY tem $FILES_SUM arquivos."
fi

